---
alertmanager_version: "0.26.0"
alertmanager_port: 9093
alertmanager_checksum: "{{ vault_alertmanager_checksum | default('') }}"
alertmanager_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ('arm64' if ansible_architecture == 'aarch64' else ansible_architecture) }}"
smtp_host: "{{ vault_smtp_host | default('localhost') }}"
smtp_from: "{{ vault_smtp_from | default('alerts@infrawatch.local') }}"
smtp_user: "{{ vault_smtp_user | default('') }}"
smtp_pass: "{{ vault_smtp_pass | default('') }}"
alert_email: "{{ vault_alert_email | default('admin@localhost') }}"
discord_webhook: "{{ vault_discord_webhook | default('') }}"